# Generated by Django 2.2.5 on 2020-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200404_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='like',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='low_res_pic',
        ),
        migrations.RemoveField(
            model_name='places',
            name='price_level',
        ),
        migrations.AddField(
            model_name='comments',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
