# Generated by Django 2.2.5 on 2020-08-23 11:06

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200821_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 15, 36, 47, 833679)),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to=core.models.place_image_path),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 15, 36, 47, 834679)),
        ),
        migrations.AlterField(
            model_name='places',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
